# Generated by Django 4.2.6 on 2023-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bonus_salgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='no_of_employee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
