# Generated by Django 4.2.6 on 2023-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department_no_of_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_url',
            field=models.URLField(default='https://django.in'),
        ),
    ]
